apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        livenessProbe:
          # exec:
            # command:
            # - mysql
            # - -uroot
            # - -p123456
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          timeoutSeconds: 1
          failureThreshold: 1
        resources:
          requests:
            cpu: 200m
            memory: 64M
          limits:
            cpu: 500m
            memory: 256M