apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: kubeguide/tomcat-app:v1
        ports:
        - containerPort: 8080
          hostPort: 23333 #容器端口直接暴露给主机
        env:
        - name: MJ_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: cm
              key: mjkey
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 7
          failureThreshold: 1
        resources:
          requests:
            cpu: 200m
            memory: 64M
          limits:
            cpu: 500m
            memory: 256M