apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myweb
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: myweb
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
