apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
  template:
    metadata:
      labels:
        app: swagger
    spec:
      containers:
      - name: swagger
        image: swaggerapi/swagger-ui:latest